name: Jdream
version: 1.0
main: dev.soranzo.Jdream
api-version: '26.1.2'
description: Integrates a discord server with minecraft server
dependencies:
  server:
    ChronoStore:
      load: BEFORE
      required: false